acct/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from django.contrib.auth import views as auth_view

app_name = 'acct'

urlpatterns = [
    path('', customer_login, name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name='acct/logout.html'), name='logout'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customer/', include('motest.urls')),
    path('', include( 'acct.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <title>Data Upload Page{% block title %}{% endblock %}</title>
</head>
<body>

<div class="container">
    <header class="header clearfix">
        <nav class="navbar navbar-expand-lg navbar-light bg-warning" >
            <a class="navbar-brand text-white" href="/">Dstagram</a>
            <ul class="nav">
                {% if user.is_authenticated %}
                    <li class="nav-item"><a href="{ % url 'motest:motest_detail_slug' %}" class="nav-link text-white">{{user.get_username}}</a></li>
                    <li class="nav-item"><a href="{% url 'motest:motest_detail_slug' user.slug %}" class="nav-link text-white">Movie Data</a></li>
                    <li class="nav-item"><a href="{% url 'acct:logout' %}" class="nav-link text-white">Logout</a></li>
                {% else %}
                <li class="nav-item"><a href="{% url 'acct:login' %}" class="nav-link">Login</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
    {% block content %}
    {% endblock %}
<br><br>
<footer class="bg-warning text-center text-white">

  <!-- Copyright -->
  <div class="text-center p-3">
    © 2020 Copyright:
    <a class="text-white" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
  <!-- Copyright -->
</footer>
</div>


</body>
</html>

templates/messages.html
{% if messages %}
  {% for message in messages %}
    <div class="alert alert-dismissible alert-success">
      <button type="button" class="close" data-dismiss="alert">
      ×
      </button>
      {{message}}
    </div>
 {% endfor %}
{% endif %}